export enum LiguiTypes {
  RESOURCE_LOADER = 'RESOURCE_LOADER',
  LOCALIZATION_LOADER = 'LOCALIZATION_LOADER',
  RESOURCE_SCOPE = 'RESOURCE_SCOPE',
  LOCALIZATION_SCOPE = 'LOCALIZATION_SCOPE',
  EVENT_BUS_SERVICE = 'EVENT_BUS_SERVICE',
  STORE_SERVICE = 'STORE_SERVICE',
  RESOURCE_SERVICE = 'RESOURCE_SERVICE',
  LOCALIZATION_SERVICE = 'LOCALIZATION_SERVICE',
  JSX_SERVICE = 'JSX_SERVICE',
  REST_SERVICE = 'REST_SERVICE'
}
